name: Build App
run-name: Build App on push
on: workflow_dispatch
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.12.3'
          spec: 'app.py'
          upload_exe_with_name: 'BlenderCMDLauncher'
          options: --onefile, --name "BlenderCMDLauncher", --windowed, 